const CatActionTypes = {
  FETCH_CATS_START: "FETCH_CATS_START",
  FETCH_CATS_SUCCESS: "FETCH_CATS_SUCCESS",
  FETCH_CATS_FAILURE: "FETCH_CATS_FAILURE",
  LOAD_MORE_CATS_START: "LOAD_MORE_CATS_START",
  LOAD_MORE_CATS_SUCCESS: "LOAD_MORE_CATS_SUCCESS",
  LOAD_MORE_CATS_FAILURE: "LOAD_MORE_CATS_FAILURE",
  FETCH_CAT_START: "FETCH_CAT_START",
  FETCH_CAT_SUCCESS: "FETCH_CAT_SUCCESS",
  FETCH_CAT_FAILURE: "FETCH_CAT_FAILURE",
  CLEAR_CATS: "CLEAR_CATS",
};

export default CatActionTypes;
