const BreedActionTypes = {
  SET_CURRENT_BREED: "SET_CURRENT_BREED",
  FETCH_BREEDS_START: "FETCH_BREEDS_START",
  FETCH_BREEDS_SUCCESS: "FETCH_BREEDS_SUCCESS",
  FETCH_BREEDS_FAILURE: "FETCH_BREEDS_FAILURE",
};

export default BreedActionTypes;
